= Autorepairs project - Spring Security configured with JWT

== This is a demo project for autorepairs shop which maintains a database about parts for vehicles.

* You can register a new user
* You can authenticate/log a user
* Spareparts for the moment are filters, rims and tyres. 
* Anyone can see all the spareparts as they are public
* Only authenticated users can create new sparepart items, and update them
* Only authenticated users with admin role has the authority:
    - to delete spareparts from the database
    - to see all users or a specific user or delete a user
* The database comes with initially generated data (`the init package`) based on:  the OPEN-CLOSE principle or the rest web client
* We save the data in MySQL database using Spring Data and Hibernate
* We use a bean exposing the Pbkdf2PasswordEncoder() PasswordEncoder - so passwords are saved in the database encoded
* MapStruct and ModelMapper are used in the project. Only one Mapstruct instance is used for several spareparts and the user - when bigger project, separate mapstruct instance for each type of entity is the preferable way of implementing
* The `SecurityConfigNewSpring.java` class in `config` package is the implementation of the new Spring Security configuration way. The `SecurityConfig.java` is the old way.
* In order to start testing the project on POSTMAN, you might better look also the documentation of the other project https://github.com/svilkata/springsecurity-with-jwt/tree/master/JWT-SimpleDemo[JWT-SimpleDemo] -
a bearer JWT token should be added as an Authorization header for all authenticated https requests.
* Sample request info (endpoint and body) are given in comments above each controller in the code of the `web` folder.
* We return a response to endpoint - with body DTO, empty body, with simple message or with error message

* Web layer / service layer
    - Working on the web controller layer mainly with DTOs, and working on the service layer mainly with entities. We could also arrange the service layer to always return to the web layer only entities or only DTOs.
    - Exception handling is invoked either on the service layer or on the web controller layer. We could arrange this to happen on only one layer
    - We could also arrange the code in such a way that: exceptions are invoked only on the web layer / or only on the service layer


* We process the exceptions with the @ControllerAdvice approach


// creteOneRimViaRestWebClientAuthorizedUser


